/*
 *
 * UserActions constants
 *
 */
export const GET_USER_LIST_ACTION = 'app/UserActions/GET_USER_LIST_ACTION';
export const GET_USER_LIST_SUCCESS_ACTION = 'app/UserActions/GET_USER_LIST_SUCCESS_ACTION';
export const GET_USER_LIST_ERROR_ACTION = 'app/UserActions/GET_USER_LIST_ERROR_ACTION';


export const GET_SEARCHED_USER_LIST_ACTION = 'app/UserActions/GET_SEARCHED_USER_LIST_ACTION';
export const GET_SEARCHED_USER_LIST_SUCCESS_ACTION = 'app/UserActions/GET_SEARCHED_USER_LIST_SUCCESS_ACTION';
export const GET_SEARCHED_USER_LIST_ERROR_ACTION = 'app/UserActions/GET_SEARCHED_USER_LIST_ERROR_ACTION';